version: "3.9"

services:
  postgres:
    image: postgres:17.7-bookworm
    container_name: nova-db
    restart: always

    environment:
      POSTGRES_USER: adm
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nova-db
      PGDATA: /var/lib/postgresql/data/pgdata

    ports:
      - "127.0.0.1:5434:5432"

    volumes:
      - data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d:ro

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U adm -d pms"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  data: